spring.application.name=code

management.endpoint.health.show-details=always
management.health.db.enabled=true

spring.datasource.url=jdbc:mysql://172.21.124.137/inventory?usessl=false
spring.datasource.username=root
spring.datasource.password=jjFofIPSZRBmOwVDKM7ks0Pp
spring.data.mongodb.uri=mongodb://root:GTGyElVNQ5wB9ElutEqDEjsC@172.21.158.253:27017/library?authSource=admin